### ISSUE TITLE
'grunt' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by AmitAKB** [rubenv/grunt-git#123]
Hello Team,

I am using window-7 OS. I have already install grunt globally, but I tried to start grunt then ## 'grunt' is not recognized as an internal or external command" is message shows.

install cmd: npm install -g grunt-cli
Grunt install on this path: Users\user_name\AppData\Roaming\npm\node_modules\grunt-cli

Please suggest me what is the wrong?

Regards & Thanks,
Amit

**Comment by rubenv** [comment]
Hi, this sounds like a grunt problem, not a grunt-git problem. You're best off looking for help at http://gruntjs.com/

**Comment by AmitAKB** [comment]
Thanks for reply, 
I'm using same site( http://gruntjs.com/) and also follow same steps in this site. 
but grunt installation completed successfully after that I'm type the grunt then show the above error message.

**Comment by rubenv** [comment]
Sorry, can't help you, not a Windows user myself.

Also, this has nothing to do with grunt-git, so this is not the right place to ask for help.

**Comment by AmitAKB** [comment]
Okay
